version: '3'

services:
  jobspy-api:
    build: .
    image: jobspy-docker-api-dev
    container_name: jobspy-docker-api-dev
    ports:
      - "8000:8000"
    env_file:
      - .env
      - .env.local  # Load .env.local to override .env values
    environment:
      # The following values intentionally override .env settings for development
      # These hardcoded values ensure consistent behavior in development environment
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - ENABLE_API_KEY_AUTH=true
      - API_KEYS=${API_KEYS:-dev-key-123}  # Use from .env.local or default to dev-key
      - RATE_LIMIT_ENABLED=true
      - ENABLE_CACHE=true
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
