name: Release Pipeline

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    - name: Run tests
      run: pytest --cov=app tests/
  
  build_and_publish_docker:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set environment variables
      run: |
        echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/jobspy-api:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/jobspy-api:${{ env.VERSION }}
    
  create_github_release:
    needs: build_and_publish_docker
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Generate release notes
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        PREVIOUS_TAG=$(git tag --sort=-version:refname | head -n 2 | tail -n 1)
        if [ -z "$PREVIOUS_TAG" ]; then
          echo "## Changes in $VERSION" > release_notes.md
          echo "* First official release" >> release_notes.md
        else
          echo "## Changes in $VERSION since $PREVIOUS_TAG" > release_notes.md
          git log --pretty=format:"* %s (%h)" $PREVIOUS_TAG..HEAD >> release_notes.md
        fi
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: release_notes.md
        draft: false
        prerelease: false
